# .goreleaser.yaml

dockers:
  - image_templates:
      - "yurianko/clonis:{{ .Version }}"
      - "yurianko/clonis:latest"
    
    use: buildx
    
    goos: linux
    goarch: amd64
    
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"