# .goreleaser.yaml
version: 2

builds:
  - id: clonis
    main: ./cmd/server/main.go 
    binary: clonis
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows 
    goarch:
      - amd64
      - arm64
      
dockers:
  - image_templates:
      - "yurianko/clonis:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - image_templates:
      - "yurianko/clonis:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

docker_manifests:
  - name_template: "yurianko/clonis:{{ .Version }}"
    image_templates:
      - "yurianko/clonis:{{ .Version }}-amd64"
      - "yurianko/clonis:{{ .Version }}-arm64"

  - name_template: "yurianko/clonis:latest"
    image_templates:
      - "yurianko/clonis:{{ .Version }}-amd64"
      - "yurianko/clonis:{{ .Version }}-arm64"